import axios from "axios";
import { useState } from "react";

const AddAddress = () => {
    let countryList = [
        {name:'select country'},
        { name: 'Afghanistan', code: 'AF' },
        { name: 'Åland Islands', code: 'AX' },
        { name: 'Albania', code: 'AL' },
        { name: 'Algeria', code: 'DZ' },
        { name: 'American Samoa', code: 'AS' },
        { name: 'AndorrA', code: 'AD' },
        { name: 'Angola', code: 'AO' },
        { name: 'Anguilla', code: 'AI' },
        { name: 'Antarctica', code: 'AQ' },
        { name: 'Antigua and Barbuda', code: 'AG' },
        { name: 'Argentina', code: 'AR' },
        { name: 'Armenia', code: 'AM' },
        { name: 'Aruba', code: 'AW' },
        { name: 'Australia', code: 'AU' },
        { name: 'Austria', code: 'AT' },
        { name: 'Azerbaijan', code: 'AZ' },
        { name: 'Bahamas', code: 'BS' },
        { name: 'Bahrain', code: 'BH' },
        { name: 'Bangladesh', code: 'BD' },
        { name: 'Barbados', code: 'BB' },
        { name: 'Belarus', code: 'BY' },
        { name: 'Belgium', code: 'BE' },
        { name: 'Belize', code: 'BZ' },
        { name: 'Benin', code: 'BJ' },
        { name: 'Bermuda', code: 'BM' },
        { name: 'Bhutan', code: 'BT' },
        { name: 'Bolivia', code: 'BO' },
        { name: 'Bosnia and Herzegovina', code: 'BA' },
        { name: 'Botswana', code: 'BW' },
        { name: 'Bouvet Island', code: 'BV' },
        { name: 'Brazil', code: 'BR' },
        { name: 'British Indian Ocean Territory', code: 'IO' },
        { name: 'Brunei Darussalam', code: 'BN' },
        { name: 'Bulgaria', code: 'BG' },
        { name: 'Burkina Faso', code: 'BF' },
        { name: 'Burundi', code: 'BI' },
        { name: 'Cambodia', code: 'KH' },
        { name: 'Cameroon', code: 'CM' },
        { name: 'Canada', code: 'CA' },
        { name: 'Cape Verde', code: 'CV' },
        { name: 'Cayman Islands', code: 'KY' },
        { name: 'Central African Republic', code: 'CF' },
        { name: 'Chad', code: 'TD' },
        { name: 'Chile', code: 'CL' },
        { name: 'China', code: 'CN' },
        { name: 'Christmas Island', code: 'CX' },
        { name: 'Cocos (Keeling) Islands', code: 'CC' },
        { name: 'Colombia', code: 'CO' },
        { name: 'Comoros', code: 'KM' },
        { name: 'Congo', code: 'CG' },
        { name: 'Congo, The Democratic Republic of the', code: 'CD' },
        { name: 'Cook Islands', code: 'CK' },
        { name: 'Costa Rica', code: 'CR' },
        { name: 'Cote D\'Ivoire', code: 'CI' },
        { name: 'Croatia', code: 'HR' },
        { name: 'Cuba', code: 'CU' },
        { name: 'Cyprus', code: 'CY' },
        { name: 'Czech Republic', code: 'CZ' },
        { name: 'Denmark', code: 'DK' },
        { name: 'Djibouti', code: 'DJ' },
        { name: 'Dominica', code: 'DM' },
        { name: 'Dominican Republic', code: 'DO' },
        { name: 'Ecuador', code: 'EC' },
        { name: 'Egypt', code: 'EG' },
        { name: 'El Salvador', code: 'SV' },
        { name: 'Equatorial Guinea', code: 'GQ' },
        { name: 'Eritrea', code: 'ER' },
        { name: 'Estonia', code: 'EE' },
        { name: 'Ethiopia', code: 'ET' },
        { name: 'Falkland Islands (Malvinas)', code: 'FK' },
        { name: 'Faroe Islands', code: 'FO' },
        { name: 'Fiji', code: 'FJ' },
        { name: 'Finland', code: 'FI' },
        { name: 'France', code: 'FR' },
        { name: 'French Guiana', code: 'GF' },
        { name: 'French Polynesia', code: 'PF' },
        { name: 'French Southern Territories', code: 'TF' },
        { name: 'Gabon', code: 'GA' },
        { name: 'Gambia', code: 'GM' },
        { name: 'Georgia', code: 'GE' },
        { name: 'Germany', code: 'DE' },
        { name: 'Ghana', code: 'GH' },
        { name: 'Gibraltar', code: 'GI' },
        { name: 'Greece', code: 'GR' },
        { name: 'Greenland', code: 'GL' },
        { name: 'Grenada', code: 'GD' },
        { name: 'Guadeloupe', code: 'GP' },
        { name: 'Guam', code: 'GU' },
        { name: 'Guatemala', code: 'GT' },
        { name: 'Guernsey', code: 'GG' },
        { name: 'Guinea', code: 'GN' },
        { name: 'Guinea-Bissau', code: 'GW' },
        { name: 'Guyana', code: 'GY' },
        { name: 'Haiti', code: 'HT' },
        { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
        { name: 'Holy See (Vatican City State)', code: 'VA' },
        { name: 'Honduras', code: 'HN' },
        { name: 'Hong Kong', code: 'HK' },
        { name: 'Hungary', code: 'HU' },
        { name: 'Iceland', code: 'IS' },
        { name: 'India', code: 'IN' },
        { name: 'Indonesia', code: 'ID' },
        { name: 'Iran, Islamic Republic Of', code: 'IR' },
        { name: 'Iraq', code: 'IQ' },
        { name: 'Ireland', code: 'IE' },
        { name: 'Isle of Man', code: 'IM' },
        { name: 'Israel', code: 'IL' },
        { name: 'Italy', code: 'IT' },
        { name: 'Jamaica', code: 'JM' },
        { name: 'Japan', code: 'JP' },
        { name: 'Jersey', code: 'JE' },
        { name: 'Jordan', code: 'JO' },
        { name: 'Kazakhstan', code: 'KZ' },
        { name: 'Kenya', code: 'KE' },
        { name: 'Kiribati', code: 'KI' },
        { name: 'Korea, Democratic People\'S Republic of', code: 'KP' },
        { name: 'Korea, Republic of', code: 'KR' },
        { name: 'Kuwait', code: 'KW' },
        { name: 'Kyrgyzstan', code: 'KG' },
        { name: 'Lao People\'S Democratic Republic', code: 'LA' },
        { name: 'Latvia', code: 'LV' },
        { name: 'Lebanon', code: 'LB' },
        { name: 'Lesotho', code: 'LS' },
        { name: 'Liberia', code: 'LR' },
        { name: 'Libyan Arab Jamahiriya', code: 'LY' },
        { name: 'Liechtenstein', code: 'LI' },
        { name: 'Lithuania', code: 'LT' },
        { name: 'Luxembourg', code: 'LU' },
        { name: 'Macao', code: 'MO' },
        { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
        { name: 'Madagascar', code: 'MG' },
        { name: 'Malawi', code: 'MW' },
        { name: 'Malaysia', code: 'MY' },
        { name: 'Maldives', code: 'MV' },
        { name: 'Mali', code: 'ML' },
        { name: 'Malta', code: 'MT' },
        { name: 'Marshall Islands', code: 'MH' },
        { name: 'Martinique', code: 'MQ' },
        { name: 'Mauritania', code: 'MR' },
        { name: 'Mauritius', code: 'MU' },
        { name: 'Mayotte', code: 'YT' },
        { name: 'Mexico', code: 'MX' },
        { name: 'Micronesia, Federated States of', code: 'FM' },
        { name: 'Moldova, Republic of', code: 'MD' },
        { name: 'Monaco', code: 'MC' },
        { name: 'Mongolia', code: 'MN' },
        { name: 'Montserrat', code: 'MS' },
        { name: 'Morocco', code: 'MA' },
        { name: 'Mozambique', code: 'MZ' },
        { name: 'Myanmar', code: 'MM' },
        { name: 'Namibia', code: 'NA' },
        { name: 'Nauru', code: 'NR' },
        { name: 'Nepal', code: 'NP' },
        { name: 'Netherlands', code: 'NL' },
        { name: 'Netherlands Antilles', code: 'AN' },
        { name: 'New Caledonia', code: 'NC' },
        { name: 'New Zealand', code: 'NZ' },
        { name: 'Nicaragua', code: 'NI' },
        { name: 'Niger', code: 'NE' },
        { name: 'Nigeria', code: 'NG' },
        { name: 'Niue', code: 'NU' },
        { name: 'Norfolk Island', code: 'NF' },
        { name: 'Northern Mariana Islands', code: 'MP' },
        { name: 'Norway', code: 'NO' },
        { name: 'Oman', code: 'OM' },
        { name: 'Pakistan', code: 'PK' },
        { name: 'Palau', code: 'PW' },
        { name: 'Palestinian Territory, Occupied', code: 'PS' },
        { name: 'Panama', code: 'PA' },
        { name: 'Papua New Guinea', code: 'PG' },
        { name: 'Paraguay', code: 'PY' },
        { name: 'Peru', code: 'PE' },
        { name: 'Philippines', code: 'PH' },
        { name: 'Pitcairn', code: 'PN' },
        { name: 'Poland', code: 'PL' },
        { name: 'Portugal', code: 'PT' },
        { name: 'Puerto Rico', code: 'PR' },
        { name: 'Qatar', code: 'QA' },
        { name: 'Reunion', code: 'RE' },
        { name: 'Romania', code: 'RO' },
        { name: 'Russian Federation', code: 'RU' },
        { name: 'RWANDA', code: 'RW' },
        { name: 'Saint Helena', code: 'SH' },
        { name: 'Saint Kitts and Nevis', code: 'KN' },
        { name: 'Saint Lucia', code: 'LC' },
        { name: 'Saint Pierre and Miquelon', code: 'PM' },
        { name: 'Saint Vincent and the Grenadines', code: 'VC' },
        { name: 'Samoa', code: 'WS' },
        { name: 'San Marino', code: 'SM' },
        { name: 'Sao Tome and Principe', code: 'ST' },
        { name: 'Saudi Arabia', code: 'SA' },
        { name: 'Senegal', code: 'SN' },
        { name: 'Serbia and Montenegro', code: 'CS' },
        { name: 'Seychelles', code: 'SC' },
        { name: 'Sierra Leone', code: 'SL' },
        { name: 'Singapore', code: 'SG' },
        { name: 'Slovakia', code: 'SK' },
        { name: 'Slovenia', code: 'SI' },
        { name: 'Solomon Islands', code: 'SB' },
        { name: 'Somalia', code: 'SO' },
        { name: 'South Africa', code: 'ZA' },
        { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
        { name: 'Spain', code: 'ES' },
        { name: 'Sri Lanka', code: 'LK' },
        { name: 'Sudan', code: 'SD' },
        { name: 'Suriname', code: 'SR' },
        { name: 'Svalbard and Jan Mayen', code: 'SJ' },
        { name: 'Swaziland', code: 'SZ' },
        { name: 'Sweden', code: 'SE' },
        { name: 'Switzerland', code: 'CH' },
        { name: 'Syrian Arab Republic', code: 'SY' },
        { name: 'Taiwan, Province of China', code: 'TW' },
        { name: 'Tajikistan', code: 'TJ' },
        { name: 'Tanzania, United Republic of', code: 'TZ' },
        { name: 'Thailand', code: 'TH' },
        { name: 'Timor-Leste', code: 'TL' },
        { name: 'Togo', code: 'TG' },
        { name: 'Tokelau', code: 'TK' },
        { name: 'Tonga', code: 'TO' },
        { name: 'Trinidad and Tobago', code: 'TT' },
        { name: 'Tunisia', code: 'TN' },
        { name: 'Turkey', code: 'TR' },
        { name: 'Turkmenistan', code: 'TM' },
        { name: 'Turks and Caicos Islands', code: 'TC' },
        { name: 'Tuvalu', code: 'TV' },
        { name: 'Uganda', code: 'UG' },
        { name: 'Ukraine', code: 'UA' },
        { name: 'United Arab Emirates', code: 'AE' },
        { name: 'United Kingdom', code: 'GB' },
        { name: 'United States', code: 'US' },
        { name: 'United States Minor Outlying Islands', code: 'UM' },
        { name: 'Uruguay', code: 'UY' },
        { name: 'Uzbekistan', code: 'UZ' },
        { name: 'Vanuatu', code: 'VU' },
        { name: 'Venezuela', code: 'VE' },
        { name: 'Viet Nam', code: 'VN' },
        { name: 'Virgin Islands, British', code: 'VG' },
        { name: 'Virgin Islands, U.S.', code: 'VI' },
        { name: 'Wallis and Futuna', code: 'WF' },
        { name: 'Western Sahara', code: 'EH' },
        { name: 'Yemen', code: 'YE' },
        { name: 'Zambia', code: 'ZM' },
        { name: 'Zimbabwe', code: 'ZW' }
    ]
    let stateList = [{
        "state":"select state"
    },
        {
            "state": "Andhra Pradesh",
            "districts": [
                "Anantapur",
                "Chittoor",
                "East Godavari",
                "Guntur",
                "Krishna",
                "Kurnool",
                "Nellore",
                "Prakasam",
                "Srikakulam",
                "Visakhapatnam",
                "Vizianagaram",
                "West Godavari",
                "YSR Kadapa"
            ]
        },
        {
            "state": "Arunachal Pradesh",
            "districts": [
                "Tawang",
                "West Kameng",
                "East Kameng",
                "Papum Pare",
                "Kurung Kumey",
                "Kra Daadi",
                "Lower Subansiri",
                "Upper Subansiri",
                "West Siang",
                "East Siang",
                "Siang",
                "Upper Siang",
                "Lower Siang",
                "Lower Dibang Valley",
                "Dibang Valley",
                "Anjaw",
                "Lohit",
                "Namsai",
                "Changlang",
                "Tirap",
                "Longding"
            ]
        },
        {
            "state": "Assam",
            "districts": [
                "Baksa",
                "Barpeta",
                "Biswanath",
                "Bongaigaon",
                "Cachar",
                "Charaideo",
                "Chirang",
                "Darrang",
                "Dhemaji",
                "Dhubri",
                "Dibrugarh",
                "Goalpara",
                "Golaghat",
                "Hailakandi",
                "Hojai",
                "Jorhat",
                "Kamrup Metropolitan",
                "Kamrup",
                "Karbi Anglong",
                "Karimganj",
                "Kokrajhar",
                "Lakhimpur",
                "Majuli",
                "Morigaon",
                "Nagaon",
                "Nalbari",
                "Dima Hasao",
                "Sivasagar",
                "Sonitpur",
                "South Salmara-Mankachar",
                "Tinsukia",
                "Udalguri",
                "West Karbi Anglong"
            ]
        },
        {
            "state": "Bihar",
            "districts": [
                "Araria",
                "Arwal",
                "Aurangabad",
                "Banka",
                "Begusarai",
                "Bhagalpur",
                "Bhojpur",
                "Buxar",
                "Darbhanga",
                "East Champaran (Motihari)",
                "Gaya",
                "Gopalganj",
                "Jamui",
                "Jehanabad",
                "Kaimur (Bhabua)",
                "Katihar",
                "Khagaria",
                "Kishanganj",
                "Lakhisarai",
                "Madhepura",
                "Madhubani",
                "Munger (Monghyr)",
                "Muzaffarpur",
                "Nalanda",
                "Nawada",
                "Patna",
                "Purnia (Purnea)",
                "Rohtas",
                "Saharsa",
                "Samastipur",
                "Saran",
                "Sheikhpura",
                "Sheohar",
                "Sitamarhi",
                "Siwan",
                "Supaul",
                "Vaishali",
                "West Champaran"
            ]
        },
        {
            "state": "Chandigarh (UT)",
            "districts": [
                "Chandigarh"
            ]
        },
        {
            "state": "Chhattisgarh",
            "districts": [
                "Balod",
                "Baloda Bazar",
                "Balrampur",
                "Bastar",
                "Bemetara",
                "Bijapur",
                "Bilaspur",
                "Dantewada (South Bastar)",
                "Dhamtari",
                "Durg",
                "Gariyaband",
                "Janjgir-Champa",
                "Jashpur",
                "Kabirdham (Kawardha)",
                "Kanker (North Bastar)",
                "Kondagaon",
                "Korba",
                "Korea (Koriya)",
                "Mahasamund",
                "Mungeli",
                "Narayanpur",
                "Raigarh",
                "Raipur",
                "Rajnandgaon",
                "Sukma",
                "Surajpur  ",
                "Surguja"
            ]
        },
        {
            "state": "Dadra and Nagar Haveli (UT)",
            "districts": [
                "Dadra & Nagar Haveli"
            ]
        },
        {
            "state": "Daman and Diu (UT)",
            "districts": [
                "Daman",
                "Diu"
            ]
        },
        {
            "state": "Delhi (NCT)",
            "districts": [
                "Central Delhi",
                "East Delhi",
                "New Delhi",
                "North Delhi",
                "North East  Delhi",
                "North West  Delhi",
                "Shahdara",
                "South Delhi",
                "South East Delhi",
                "South West  Delhi",
                "West Delhi"
            ]
        },
        {
            "state": "Goa",
            "districts": [
                "North Goa",
                "South Goa"
            ]
        },
        {
            "state": "Gujarat",
            "districts": [
                "Ahmedabad",
                "Amreli",
                "Anand",
                "Aravalli",
                "Banaskantha (Palanpur)",
                "Bharuch",
                "Bhavnagar",
                "Botad",
                "Chhota Udepur",
                "Dahod",
                "Dangs (Ahwa)",
                "Devbhoomi Dwarka",
                "Gandhinagar",
                "Gir Somnath",
                "Jamnagar",
                "Junagadh",
                "Kachchh",
                "Kheda (Nadiad)",
                "Mahisagar",
                "Mehsana",
                "Morbi",
                "Narmada (Rajpipla)",
                "Navsari",
                "Panchmahal (Godhra)",
                "Patan",
                "Porbandar",
                "Rajkot",
                "Sabarkantha (Himmatnagar)",
                "Surat",
                "Surendranagar",
                "Tapi (Vyara)",
                "Vadodara",
                "Valsad"
            ]
        },
        {
            "state": "Haryana",
            "districts": [
                "Ambala",
                "Bhiwani",
                "Charkhi Dadri",
                "Faridabad",
                "Fatehabad",
                "Gurgaon",
                "Hisar",
                "Jhajjar",
                "Jind",
                "Kaithal",
                "Karnal",
                "Kurukshetra",
                "Mahendragarh",
                "Mewat",
                "Palwal",
                "Panchkula",
                "Panipat",
                "Rewari",
                "Rohtak",
                "Sirsa",
                "Sonipat",
                "Yamunanagar"
            ]
        },
        {
            "state": "Himachal Pradesh",
            "districts": [
                "Bilaspur",
                "Chamba",
                "Hamirpur",
                "Kangra",
                "Kinnaur",
                "Kullu",
                "Lahaul &amp; Spiti",
                "Mandi",
                "Shimla",
                "Sirmaur (Sirmour)",
                "Solan",
                "Una"
            ]
        },
        {
            "state": "Jammu and Kashmir",
            "districts": [
                "Anantnag",
                "Bandipore",
                "Baramulla",
                "Budgam",
                "Doda",
                "Ganderbal",
                "Jammu",
                "Kargil",
                "Kathua",
                "Kishtwar",
                "Kulgam",
                "Kupwara",
                "Leh",
                "Poonch",
                "Pulwama",
                "Rajouri",
                "Ramban",
                "Reasi",
                "Samba",
                "Shopian",
                "Srinagar",
                "Udhampur"
            ]
        },
        {
            "state": "Jharkhand",
            "districts": [
                "Bokaro",
                "Chatra",
                "Deoghar",
                "Dhanbad",
                "Dumka",
                "East Singhbhum",
                "Garhwa",
                "Giridih",
                "Godda",
                "Gumla",
                "Hazaribag",
                "Jamtara",
                "Khunti",
                "Koderma",
                "Latehar",
                "Lohardaga",
                "Pakur",
                "Palamu",
                "Ramgarh",
                "Ranchi",
                "Sahibganj",
                "Seraikela-Kharsawan",
                "Simdega",
                "West Singhbhum"
            ]
        },
        {
            "state": "Karnataka",
            "districts": [
                "Bagalkot",
                "Ballari (Bellary)",
                "Belagavi (Belgaum)",
                "Bengaluru (Bangalore) Rural",
                "Bengaluru (Bangalore) Urban",
                "Bidar",
                "Chamarajanagar",
                "Chikballapur",
                "Chikkamagaluru (Chikmagalur)",
                "Chitradurga",
                "Dakshina Kannada",
                "Davangere",
                "Dharwad",
                "Gadag",
                "Hassan",
                "Haveri",
                "Kalaburagi (Gulbarga)",
                "Kodagu",
                "Kolar",
                "Koppal",
                "Mandya",
                "Mysuru (Mysore)",
                "Raichur",
                "Ramanagara",
                "Shivamogga (Shimoga)",
                "Tumakuru (Tumkur)",
                "Udupi",
                "Uttara Kannada (Karwar)",
                "Vijayapura (Bijapur)",
                "Yadgir"
            ]
        },
        {
            "state": "Kerala",
            "districts": [
                "Alappuzha",
                "Ernakulam",
                "Idukki",
                "Kannur",
                "Kasaragod",
                "Kollam",
                "Kottayam",
                "Kozhikode",
                "Malappuram",
                "Palakkad",
                "Pathanamthitta",
                "Thiruvananthapuram",
                "Thrissur",
                "Wayanad"
            ]
        },
        {
            "state": "Lakshadweep (UT)",
            "districts": [
                "Agatti",
                "Amini",
                "Androth",
                "Bithra",
                "Chethlath",
                "Kavaratti",
                "Kadmath",
                "Kalpeni",
                "Kilthan",
                "Minicoy"
            ]
        },
        {
            "state": "Madhya Pradesh",
            "districts": [
                "Agar Malwa",
                "Alirajpur",
                "Anuppur",
                "Ashoknagar",
                "Balaghat",
                "Barwani",
                "Betul",
                "Bhind",
                "Bhopal",
                "Burhanpur",
                "Chhatarpur",
                "Chhindwara",
                "Damoh",
                "Datia",
                "Dewas",
                "Dhar",
                "Dindori",
                "Guna",
                "Gwalior",
                "Harda",
                "Hoshangabad",
                "Indore",
                "Jabalpur",
                "Jhabua",
                "Katni",
                "Khandwa",
                "Khargone",
                "Mandla",
                "Mandsaur",
                "Morena",
                "Narsinghpur",
                "Neemuch",
                "Panna",
                "Raisen",
                "Rajgarh",
                "Ratlam",
                "Rewa",
                "Sagar",
                "Satna",
                "Sehore",
                "Seoni",
                "Shahdol",
                "Shajapur",
                "Sheopur",
                "Shivpuri",
                "Sidhi",
                "Singrauli",
                "Tikamgarh",
                "Ujjain",
                "Umaria",
                "Vidisha"
            ]
        },
        {
            "state": "Maharashtra",
            "districts": [
                "Ahmednagar",
                "Akola",
                "Amravati",
                "Aurangabad",
                "Beed",
                "Bhandara",
                "Buldhana",
                "Chandrapur",
                "Dhule",
                "Gadchiroli",
                "Gondia",
                "Hingoli",
                "Jalgaon",
                "Jalna",
                "Kolhapur",
                "Latur",
                "Mumbai City",
                "Mumbai Suburban",
                "Nagpur",
                "Nanded",
                "Nandurbar",
                "Nashik",
                "Osmanabad",
                "Palghar",
                "Parbhani",
                "Pune",
                "Raigad",
                "Ratnagiri",
                "Sangli",
                "Satara",
                "Sindhudurg",
                "Solapur",
                "Thane",
                "Wardha",
                "Washim",
                "Yavatmal"
            ]
        },
        {
            "state": "Manipur",
            "districts": [
                "Bishnupur",
                "Chandel",
                "Churachandpur",
                "Imphal East",
                "Imphal West",
                "Jiribam",
                "Kakching",
                "Kamjong",
                "Kangpokpi",
                "Noney",
                "Pherzawl",
                "Senapati",
                "Tamenglong",
                "Tengnoupal",
                "Thoubal",
                "Ukhrul"
            ]
        },
        {
            "state": "Meghalaya",
            "districts": [
                "East Garo Hills",
                "East Jaintia Hills",
                "East Khasi Hills",
                "North Garo Hills",
                "Ri Bhoi",
                "South Garo Hills",
                "South West Garo Hills ",
                "South West Khasi Hills",
                "West Garo Hills",
                "West Jaintia Hills",
                "West Khasi Hills"
            ]
        },
        {
            "state": "Mizoram",
            "districts": [
                "Aizawl",
                "Champhai",
                "Kolasib",
                "Lawngtlai",
                "Lunglei",
                "Mamit",
                "Saiha",
                "Serchhip"
            ]
        },
        {
            "state": "Nagaland",
            "districts": [
                "Dimapur",
                "Kiphire",
                "Kohima",
                "Longleng",
                "Mokokchung",
                "Mon",
                "Peren",
                "Phek",
                "Tuensang",
                "Wokha",
                "Zunheboto"
            ]
        },
        {
            "state": "Odisha",
            "districts": [
                "Angul",
                "Balangir",
                "Balasore",
                "Bargarh",
                "Bhadrak",
                "Boudh",
                "Cuttack",
                "Deogarh",
                "Dhenkanal",
                "Gajapati",
                "Ganjam",
                "Jagatsinghapur",
                "Jajpur",
                "Jharsuguda",
                "Kalahandi",
                "Kandhamal",
                "Kendrapara",
                "Kendujhar (Keonjhar)",
                "Khordha",
                "Koraput",
                "Malkangiri",
                "Mayurbhanj",
                "Nabarangpur",
                "Nayagarh",
                "Nuapada",
                "Puri",
                "Rayagada",
                "Sambalpur",
                "Sonepur",
                "Sundargarh"
            ]
        },
        {
            "state": "Puducherry (UT)",
            "districts": [
                "Karaikal",
                "Mahe",
                "Pondicherry",
                "Yanam"
            ]
        },
        {
            "state": "Punjab",
            "districts": [
                "Amritsar",
                "Barnala",
                "Bathinda",
                "Faridkot",
                "Fatehgarh Sahib",
                "Fazilka",
                "Ferozepur",
                "Gurdaspur",
                "Hoshiarpur",
                "Jalandhar",
                "Kapurthala",
                "Ludhiana",
                "Mansa",
                "Moga",
                "Muktsar",
                "Nawanshahr (Shahid Bhagat Singh Nagar)",
                "Pathankot",
                "Patiala",
                "Rupnagar",
                "Sahibzada Ajit Singh Nagar (Mohali)",
                "Sangrur",
                "Tarn Taran"
            ]
        },
        {
            "state": "Rajasthan",
            "districts": [
                "Ajmer",
                "Alwar",
                "Banswara",
                "Baran",
                "Barmer",
                "Bharatpur",
                "Bhilwara",
                "Bikaner",
                "Bundi",
                "Chittorgarh",
                "Churu",
                "Dausa",
                "Dholpur",
                "Dungarpur",
                "Hanumangarh",
                "Jaipur",
                "Jaisalmer",
                "Jalore",
                "Jhalawar",
                "Jhunjhunu",
                "Jodhpur",
                "Karauli",
                "Kota",
                "Nagaur",
                "Pali",
                "Pratapgarh",
                "Rajsamand",
                "Sawai Madhopur",
                "Sikar",
                "Sirohi",
                "Sri Ganganagar",
                "Tonk",
                "Udaipur"
            ]
        },
        {
            "state": "Sikkim",
            "districts": [
                "East Sikkim",
                "North Sikkim",
                "South Sikkim",
                "West Sikkim"
            ]
        },
        {
            "state": "Tamil Nadu",
            "districts": [
                "Ariyalur",
                "Chennai",
                "Coimbatore",
                "Cuddalore",
                "Dharmapuri",
                "Dindigul",
                "Erode",
                "Kanchipuram",
                "Kanyakumari",
                "Karur",
                "Krishnagiri",
                "Madurai",
                "Nagapattinam",
                "Namakkal",
                "Nilgiris",
                "Perambalur",
                "Pudukkottai",
                "Ramanathapuram",
                "Salem",
                "Sivaganga",
                "Thanjavur",
                "Theni",
                "Thoothukudi (Tuticorin)",
                "Tiruchirappalli",
                "Tirunelveli",
                "Tiruppur",
                "Tiruvallur",
                "Tiruvannamalai",
                "Tiruvarur",
                "Vellore",
                "Viluppuram",
                "Virudhunagar"
            ]
        },
        {
            "state": "Telangana",
            "districts": [
                "Adilabad",
                "Bhadradri Kothagudem",
                "Hyderabad",
                "Jagtial",
                "Jangaon",
                "Jayashankar Bhoopalpally",
                "Jogulamba Gadwal",
                "Kamareddy",
                "Karimnagar",
                "Khammam",
                "Komaram Bheem Asifabad",
                "Mahabubabad",
                "Mahabubnagar",
                "Mancherial",
                "Medak",
                "Medchal",
                "Nagarkurnool",
                "Nalgonda",
                "Nirmal",
                "Nizamabad",
                "Peddapalli",
                "Rajanna Sircilla",
                "Rangareddy",
                "Sangareddy",
                "Siddipet",
                "Suryapet",
                "Vikarabad",
                "Wanaparthy",
                "Warangal (Rural)",
                "Warangal (Urban)",
                "Yadadri Bhuvanagiri"
            ]
        },
        {
            "state": "Tripura",
            "districts": [
                "Dhalai",
                "Gomati",
                "Khowai",
                "North Tripura",
                "Sepahijala",
                "South Tripura",
                "Unakoti",
                "West Tripura"
            ]
        },
        {
            "state": "Uttarakhand",
            "districts": [
                "Almora",
                "Bageshwar",
                "Chamoli",
                "Champawat",
                "Dehradun",
                "Haridwar",
                "Nainital",
                "Pauri Garhwal",
                "Pithoragarh",
                "Rudraprayag",
                "Tehri Garhwal",
                "Udham Singh Nagar",
                "Uttarkashi"
            ]
        },
        {
            "state": "Uttar Pradesh",
            "districts": [
                "Agra",
                "Aligarh",
                "Allahabad",
                "Ambedkar Nagar",
                "Amethi (Chatrapati Sahuji Mahraj Nagar)",
                "Amroha (J.P. Nagar)",
                "Auraiya",
                "Azamgarh",
                "Baghpat",
                "Bahraich",
                "Ballia",
                "Balrampur",
                "Banda",
                "Barabanki",
                "Bareilly",
                "Basti",
                "Bhadohi",
                "Bijnor",
                "Budaun",
                "Bulandshahr",
                "Chandauli",
                "Chitrakoot",
                "Deoria",
                "Etah",
                "Etawah",
                "Faizabad",
                "Farrukhabad",
                "Fatehpur",
                "Firozabad",
                "Gautam Buddha Nagar",
                "Ghaziabad",
                "Ghazipur",
                "Gonda",
                "Gorakhpur",
                "Hamirpur",
                "Hapur (Panchsheel Nagar)",
                "Hardoi",
                "Hathras",
                "Jalaun",
                "Jaunpur",
                "Jhansi",
                "Kannauj",
                "Kanpur Dehat",
                "Kanpur Nagar",
                "Kanshiram Nagar (Kasganj)",
                "Kaushambi",
                "Kushinagar (Padrauna)",
                "Lakhimpur - Kheri",
                "Lalitpur",
                "Lucknow",
                "Maharajganj",
                "Mahoba",
                "Mainpuri",
                "Mathura",
                "Mau",
                "Meerut",
                "Mirzapur",
                "Moradabad",
                "Muzaffarnagar",
                "Pilibhit",
                "Pratapgarh",
                "RaeBareli",
                "Rampur",
                "Saharanpur",
                "Sambhal (Bhim Nagar)",
                "Sant Kabir Nagar",
                "Shahjahanpur",
                "Shamali (Prabuddh Nagar)",
                "Shravasti",
                "Siddharth Nagar",
                "Sitapur",
                "Sonbhadra",
                "Sultanpur",
                "Unnao",
                "Varanasi"
            ]
        },
        {
            "state": "West Bengal",
            "districts": [
                "Alipurduar",
                "Bankura",
                "Birbhum",
                "Burdwan (Bardhaman)",
                "Cooch Behar",
                "Dakshin Dinajpur (South Dinajpur)",
                "Darjeeling",
                "Hooghly",
                "Howrah",
                "Jalpaiguri",
                "Kalimpong",
                "Kolkata",
                "Malda",
                "Murshidabad",
                "Nadia",
                "North 24 Parganas",
                "Paschim Medinipur (West Medinipur)",
                "Purba Medinipur (East Medinipur)",
                "Purulia",
                "South 24 Parganas",
                "Uttar Dinajpur (North Dinajpur)"
            ]
        }
    ]
    let cityList = [
        "select city",
        "Achalpur",
        "Achhnera",
        "Adalaj",
        "Adilabad",
        "Adityapur",
        "Adoni",
        "Adoor",
        "Adra",
        "Adyar",
        "Afzalpur",
        "Agartala",
        "Agra",
        "Ahmedabad",
        "Ahmednagar",
        "Aizawl",
        "Ajmer",
        "Akola",
        "Akot",
        "Alappuzha",
        "Aligarh",
        "AlipurdUrban Agglomerationr",
        "Alirajpur",
        "Allahabad",
        "Alwar",
        "Amalapuram",
        "Amalner",
        "Ambejogai",
        "Ambikapur",
        "Amravati",
        "Amreli",
        "Amritsar",
        "Amroha",
        "Anakapalle",
        "Anand",
        "Anantapur",
        "Anantnag",
        "Anjangaon",
        "Anjar",
        "Ankleshwar",
        "Arakkonam",
        "Arambagh",
        "Araria",
        "Arrah",
        "Arsikere",
        "Aruppukkottai",
        "Arvi",
        "Arwal",
        "Asansol",
        "Asarganj",
        "Ashok Nagar",
        "Athni",
        "Attingal",
        "Aurangabad",
        "Aurangabad",
        "Azamgarh",
        "Bagaha",
        "Bageshwar",
        "Bahadurgarh",
        "Baharampur",
        "Bahraich",
        "Balaghat",
        "Balangir",
        "Baleshwar Town",
        "Ballari",
        "Balurghat",
        "Bankura",
        "Bapatla",
        "Baramula",
        "Barbil",
        "Bargarh",
        "Barh",
        "Baripada Town",
        "Barmer",
        "Barnala",
        "Barpeta",
        "Batala",
        "Bathinda",
        "Begusarai",
        "Belagavi",
        "Bellampalle",
        "Belonia",
        "Bengaluru",
        "Bettiah",
        "BhabUrban Agglomeration",
        "Bhadrachalam",
        "Bhadrak",
        "Bhagalpur",
        "Bhainsa",
        "Bharatpur",
        "Bharuch",
        "Bhatapara",
        "Bhavnagar",
        "Bhawanipatna",
        "Bheemunipatnam",
        "Bhilai Nagar",
        "Bhilwara",
        "Bhimavaram",
        "Bhiwandi",
        "Bhiwani",
        "Bhongir",
        "Bhopal",
        "Bhubaneswar",
        "Bhuj",
        "Bikaner",
        "Bilaspur",
        "Bobbili",
        "Bodhan",
        "Bokaro Steel City",
        "Bongaigaon City",
        "Brahmapur",
        "Buxar",
        "Byasanagar",
        "Chaibasa",
        "Chalakudy",
        "Chandausi",
        "Chandigarh",
        "Changanassery",
        "Charkhi Dadri",
        "Chatra",
        "Chennai",
        "Cherthala",
        "Chhapra",
        "Chhapra",
        "Chikkamagaluru",
        "Chilakaluripet",
        "Chirala",
        "Chirkunda",
        "Chirmiri",
        "Chittoor",
        "Chittur-Thathamangalam",
        "Coimbatore",
        "Cuttack",
        "Dalli-Rajhara",
        "Darbhanga",
        "Darjiling",
        "Davanagere",
        "Deesa",
        "Dehradun",
        "Dehri-on-Sone",
        "Delhi",
        "Deoghar",
        "Dhamtari",
        "Dhanbad",
        "Dharmanagar",
        "Dharmavaram",
        "Dhenkanal",
        "Dhoraji",
        "Dhubri",
        "Dhule",
        "Dhuri",
        "Dibrugarh",
        "Dimapur",
        "Diphu",
        "Dumka",
        "Dumraon",
        "Durg",
        "Eluru",
        "English Bazar",
        "Erode",
        "Etawah",
        "Faridabad",
        "Faridkot",
        "Farooqnagar",
        "Fatehabad",
        "Fatehpur Sikri",
        "Fazilka",
        "Firozabad",
        "Firozpur Cantt.",
        "Firozpur",
        "Forbesganj",
        "Gadwal",
        "Gandhinagar",
        "Gangarampur",
        "Ganjbasoda",
        "Gaya",
        "Giridih",
        "Goalpara",
        "Gobichettipalayam",
        "Gobindgarh",
        "Godhra",
        "Gohana",
        "Gokak",
        "Gooty",
        "Gopalganj",
        "Gudivada",
        "Gudur",
        "Gumia",
        "Guntakal",
        "Guntur",
        "Gurdaspur",
        "Gurgaon",
        "Guruvayoor",
        "Guwahati",
        "Gwalior",
        "Habra",
        "Hajipur",
        "Haldwani-cum-Kathgodam",
        "Hansi",
        "Hapur",
        "Hardoi ",
        "Hardwar",
        "Hazaribag",
        "Hindupur",
        "Hisar",
        "Hoshiarpur",
        "Hubli-Dharwad",
        "Hugli-Chinsurah",
        "Hyderabad",
        "Ichalkaranji",
        "Imphal",
        "Indore",
        "Itarsi",
        "Jabalpur",
        "Jagdalpur",
        "Jaggaiahpet",
        "Jagraon",
        "Jagtial",
        "Jaipur",
        "Jalandhar Cantt.",
        "Jalandhar",
        "Jalpaiguri",
        "Jamalpur",
        "Jammalamadugu",
        "Jammu",
        "Jamnagar",
        "Jamshedpur",
        "Jamui",
        "Jangaon",
        "Jatani",
        "Jehanabad",
        "Jhansi",
        "Jhargram",
        "Jharsuguda",
        "Jhumri Tilaiya",
        "Jind",
        "Jodhpur",
        "Jorhat",
        "Kadapa",
        "Kadi",
        "Kadiri",
        "Kagaznagar",
        "Kailasahar",
        "Kaithal",
        "Kakinada",
        "Kalimpong",
        "Kalpi",
        "Kalyan-Dombivali",
        "Kamareddy",
        "Kancheepuram",
        "Kandukur",
        "Kanhangad",
        "Kannur",
        "Kanpur",
        "Kapadvanj",
        "Kapurthala",
        "Karaikal",
        "Karimganj",
        "Karimnagar",
        "Karjat",
        "Karnal",
        "Karur",
        "Karwar",
        "Kasaragod",
        "Kashipur",
        "KathUrban Agglomeration",
        "Katihar",
        "Kavali",
        "Kayamkulam",
        "Kendrapara",
        "Kendujhar",
        "Keshod",
        "Khair",
        "Khambhat",
        "Khammam",
        "Khanna",
        "Kharagpur",
        "Kharar",
        "Khowai",
        "Kishanganj",
        "Kochi",
        "Kodungallur",
        "Kohima",
        "Kolar",
        "Kolkata",
        "Kollam",
        "Koratla",
        "Korba",
        "Kot Kapura",
        "Kota",
        "Kothagudem",
        "Kottayam",
        "Kovvur",
        "Koyilandy",
        "Kozhikode",
        "Kunnamkulam",
        "Kurnool",
        "Kyathampalle",
        "Lachhmangarh",
        "Ladnu",
        "Ladwa",
        "Lahar",
        "Laharpur",
        "Lakheri",
        "Lakhimpur",
        "Lakhisarai",
        "Lakshmeshwar",
        "Lal Gopalganj Nindaura",
        "Lalganj",
        "Lalganj",
        "Lalgudi",
        "Lalitpur",
        "Lalsot",
        "Lanka",
        "Lar",
        "Lathi",
        "Latur",
        "Lilong",
        "Limbdi",
        "Lingsugur",
        "Loha",
        "Lohardaga",
        "Lonar",
        "Lonavla",
        "Longowal",
        "Loni",
        "Losal",
        "Lucknow",
        "Ludhiana",
        "Lumding",
        "Lunawada",
        "Lunglei",
        "Macherla",
        "Machilipatnam",
        "Madanapalle",
        "Maddur",
        "Madhepura",
        "Madhubani",
        "Madhugiri",
        "Madhupur",
        "Madikeri",
        "Madurai",
        "Magadi",
        "Mahad",
        "Mahalingapura",
        "Maharajganj",
        "Maharajpur",
        "Mahasamund",
        "Mahbubnagar",
        "Mahe",
        "Mahemdabad",
        "Mahendragarh",
        "Mahesana",
        "Mahidpur",
        "Mahnar Bazar",
        "Mahuva",
        "Maihar",
        "Mainaguri",
        "Makhdumpur",
        "Makrana",
        "Malaj Khand",
        "Malappuram",
        "Malavalli",
        "Malda",
        "Malegaon",
        "Malerkotla",
        "Malkangiri",
        "Malkapur",
        "Malout",
        "Malpura",
        "Malur",
        "Manachanallur",
        "Manasa",
        "Manavadar",
        "Manawar",
        "Mancherial",
        "Mandalgarh",
        "Mandamarri",
        "Mandapeta",
        "Mandawa",
        "Mandi Dabwali",
        "Mandi",
        "Mandideep",
        "Mandla",
        "Mandsaur",
        "Mandvi",
        "Mandya",
        "Manendragarh",
        "Maner",
        "Mangaldoi",
        "Mangaluru",
        "Mangalvedhe",
        "Manglaur",
        "Mangrol",
        "Mangrol",
        "Mangrulpir",
        "Manihari",
        "Manjlegaon",
        "Mankachar",
        "Manmad",
        "Mansa",
        "Mansa",
        "Manuguru",
        "Manvi",
        "Manwath",
        "Mapusa",
        "Margao",
        "Margherita",
        "Marhaura",
        "Mariani",
        "Marigaon",
        "Markapur",
        "Marmagao",
        "Masaurhi",
        "Mathabhanga",
        "Mathura",
        "Mattannur",
        "Mauganj",
        "Mavelikkara",
        "Mavoor",
        "Mayang Imphal",
        "Medak",
        "Medininagar (Daltonganj)",
        "Medinipur",
        "Meerut",
        "Mehkar",
        "Memari",
        "Merta City",
        "Mhaswad",
        "Mhow Cantonment",
        "Mhowgaon",
        "Mihijam",
        "Mira-Bhayandar",
        "Mirganj",
        "Miryalaguda",
        "Modasa",
        "Modinagar",
        "Moga",
        "Mohali",
        "Mokameh",
        "Mokokchung",
        "Monoharpur",
        "Moradabad",
        "Morena",
        "Morinda, India",
        "Morshi",
        "Morvi",
        "Motihari",
        "Motipur",
        "Mount Abu",
        "Mudabidri",
        "Mudalagi",
        "Muddebihal",
        "Mudhol",
        "Mukerian",
        "Mukhed",
        "Muktsar",
        "Mul",
        "Mulbagal",
        "Multai",
        "Mumbai",
        "Mundargi",
        "Mundi",
        "Mungeli",
        "Munger",
        "Murliganj",
        "Murshidabad",
        "Murtijapur",
        "Murwara (Katni)",
        "Musabani",
        "Mussoorie",
        "Muvattupuzha",
        "Muzaffarpur",
        "Mysore",
        "Nabadwip",
        "Nabarangapur",
        "Nabha",
        "Nadbai",
        "Nadiad",
        "Nagaon",
        "Nagapattinam",
        "Nagar",
        "Nagari",
        "Nagarkurnool",
        "Nagaur",
        "Nagda",
        "Nagercoil",
        "Nagina",
        "Nagla",
        "Nagpur",
        "Nahan",
        "Naharlagun",
        "Naidupet",
        "Naihati",
        "Naila Janjgir",
        "Nainital",
        "Nainpur",
        "Najibabad",
        "Nakodar",
        "Nakur",
        "Nalbari",
        "Namagiripettai",
        "Namakkal",
        "Nanded-Waghala",
        "Nandgaon",
        "Nandivaram-Guduvancheri",
        "Nandura",
        "Nandurbar",
        "Nandyal",
        "Nangal",
        "Nanjangud",
        "Nanjikottai",
        "Nanpara",
        "Narasapuram",
        "Narasaraopet",
        "Naraura",
        "Narayanpet",
        "Nargund",
        "Narkatiaganj",
        "Narkhed",
        "Narnaul",
        "Narsinghgarh",
        "Narsinghgarh",
        "Narsipatnam",
        "Narwana",
        "Nashik",
        "Nasirabad",
        "Natham",
        "Nathdwara",
        "Naugachhia",
        "Naugawan Sadat",
        "Nautanwa",
        "Navalgund",
        "Navsari",
        "Nawabganj",
        "Nawada",
        "Nawanshahr",
        "Nawapur",
        "Nedumangad",
        "Neem-Ka-Thana",
        "Neemuch",
        "Nehtaur",
        "Nelamangala",
        "Nellikuppam",
        "Nellore",
        "Nepanagar",
        "New Delhi",
        "Neyveli (TS)",
        "Neyyattinkara",
        "Nidadavole",
        "Nilambur",
        "Nilanga",
        "Nimbahera",
        "Nirmal",
        "Niwai",
        "Niwari",
        "Nizamabad",
        "Nohar",
        "Noida",
        "Nokha",
        "Nokha",
        "Nongstoin",
        "Noorpur",
        "North Lakhimpur",
        "Nowgong",
        "Nowrozabad (Khodargama)",
        "Nuzvid",
        "O' Valley",
        "Obra",
        "Oddanchatram",
        "Ongole",
        "Orai",
        "Osmanabad",
        "Ottappalam",
        "Ozar",
        "P.N.Patti",
        "Pachora",
        "Pachore",
        "Pacode",
        "Padmanabhapuram",
        "Padra",
        "Padrauna",
        "Paithan",
        "Pakaur",
        "Palacole",
        "Palai",
        "Palakkad",
        "Palampur",
        "Palani",
        "Palanpur",
        "Palasa Kasibugga",
        "Palghar",
        "Pali",
        "Pali",
        "Palia Kalan",
        "Palitana",
        "Palladam",
        "Pallapatti",
        "Pallikonda",
        "Palwal",
        "Palwancha",
        "Panagar",
        "Panagudi",
        "Panaji",
        "Panamattom",
        "Panchkula",
        "Panchla",
        "Pandharkaoda",
        "Pandharpur",
        "Pandhurna",
        "PandUrban Agglomeration",
        "Panipat",
        "Panna",
        "Panniyannur",
        "Panruti",
        "Panvel",
        "Pappinisseri",
        "Paradip",
        "Paramakudi",
        "Parangipettai",
        "Parasi",
        "Paravoor",
        "Parbhani",
        "Pardi",
        "Parlakhemundi",
        "Parli",
        "Partur",
        "Parvathipuram",
        "Pasan",
        "Paschim Punropara",
        "Pasighat",
        "Patan",
        "Pathanamthitta",
        "Pathankot",
        "Pathardi",
        "Pathri",
        "Patiala",
        "Patna",
        "Patratu",
        "Pattamundai",
        "Patti",
        "Pattran",
        "Pattukkottai",
        "Patur",
        "Pauni",
        "Pauri",
        "Pavagada",
        "Pedana",
        "Peddapuram",
        "Pehowa",
        "Pen",
        "Perambalur",
        "Peravurani",
        "Peringathur",
        "Perinthalmanna",
        "Periyakulam",
        "Periyasemur",
        "Pernampattu",
        "Perumbavoor",
        "Petlad",
        "Phagwara",
        "Phalodi",
        "Phaltan",
        "Phillaur",
        "Phulabani",
        "Phulera",
        "Phulpur",
        "Phusro",
        "Pihani",
        "Pilani",
        "Pilibanga",
        "Pilibhit",
        "Pilkhuwa",
        "Pindwara",
        "Pinjore",
        "Pipar City",
        "Pipariya",
        "Piriyapatna",
        "Piro",
        "Pithampur",
        "Pithapuram",
        "Pithoragarh",
        "Pollachi",
        "Polur",
        "Pondicherry",
        "Ponnani",
        "Ponneri",
        "Ponnur",
        "Porbandar",
        "Porsa",
        "Port Blair",
        "Powayan",
        "Prantij",
        "Pratapgarh",
        "Pratapgarh",
        "Prithvipur",
        "Proddatur",
        "Pudukkottai",
        "Pudupattinam",
        "Pukhrayan",
        "Pulgaon",
        "Puliyankudi",
        "Punalur",
        "Punch",
        "Pune",
        "Punganur",
        "Punjaipugalur",
        "Puranpur",
        "Puri",
        "Purna",
        "Purnia",
        "PurqUrban Agglomerationzi",
        "Purulia",
        "Purwa",
        "Pusad",
        "Puthuppally",
        "Puttur",
        "Puttur",
        "Qadian",
        "Raayachuru",
        "Rabkavi Banhatti",
        "Radhanpur",
        "Rae Bareli",
        "Rafiganj",
        "Raghogarh-Vijaypur",
        "Raghunathganj",
        "Raghunathpur",
        "Rahatgarh",
        "Rahuri",
        "Raiganj",
        "Raigarh",
        "Raikot",
        "Raipur",
        "Rairangpur",
        "Raisen",
        "Raisinghnagar",
        "Rajagangapur",
        "Rajahmundry",
        "Rajakhera",
        "Rajaldesar",
        "Rajam",
        "Rajampet",
        "Rajapalayam",
        "Rajauri",
        "Rajgarh (Alwar)",
        "Rajgarh (Churu)",
        "Rajgarh",
        "Rajgir",
        "Rajkot",
        "Rajnandgaon",
        "Rajpipla",
        "Rajpura",
        "Rajsamand",
        "Rajula",
        "Rajura",
        "Ramachandrapuram",
        "Ramagundam",
        "Ramanagaram",
        "Ramanathapuram",
        "Ramdurg",
        "Rameshwaram",
        "Ramganj Mandi",
        "Ramgarh",
        "Ramnagar",
        "Ramnagar",
        "Ramngarh",
        "Rampur Maniharan",
        "Rampur",
        "Rampura Phul",
        "Rampurhat",
        "Ramtek",
        "Ranaghat",
        "Ranavav",
        "Ranchi",
        "Ranebennuru",
        "Rangia",
        "Rania",
        "Ranibennur",
        "Ranipet",
        "Rapar",
        "Rasipuram",
        "Rasra",
        "Ratangarh",
        "Rath",
        "Ratia",
        "Ratlam",
        "Ratnagiri",
        "Rau",
        "Raurkela",
        "Raver",
        "Rawatbhata",
        "Rawatsar",
        "Raxaul Bazar",
        "Rayachoti",
        "Rayadurg",
        "Rayagada",
        "Reengus",
        "Rehli",
        "Renigunta",
        "Renukoot",
        "Reoti",
        "Repalle",
        "Revelganj",
        "Rewa",
        "Rewari",
        "Rishikesh",
        "Risod",
        "Robertsganj",
        "Robertson Pet",
        "Rohtak",
        "Ron",
        "Roorkee",
        "Rosera",
        "Rudauli",
        "Rudrapur",
        "Rudrapur",
        "Rupnagar",
        "Sabalgarh",
        "Sadabad",
        "Sadalagi",
        "Sadasivpet",
        "Sadri",
        "Sadulpur",
        "Sadulshahar",
        "Safidon",
        "Safipur",
        "Sagar",
        "Sagara",
        "Sagwara",
        "Saharanpur",
        "Saharsa",
        "Sahaspur",
        "Sahaswan",
        "Sahawar",
        "Sahibganj",
        "Sahjanwa",
        "Saidpur",
        "Saiha",
        "Sailu",
        "Sainthia",
        "Sakaleshapura",
        "Sakti",
        "Salaya",
        "Salem",
        "Salur",
        "Samalkha",
        "Samalkot",
        "Samana",
        "Samastipur",
        "Sambalpur",
        "Sambhal",
        "Sambhar",
        "Samdhan",
        "Samthar",
        "Sanand",
        "Sanawad",
        "Sanchore",
        "Sandi",
        "Sandila",
        "Sanduru",
        "Sangamner",
        "Sangareddy",
        "Sangaria",
        "Sangli",
        "Sangole",
        "Sangrur",
        "Sankarankovil",
        "Sankari",
        "Sankeshwara",
        "Santipur",
        "Sarangpur",
        "Sardarshahar",
        "Sardhana",
        "Sarni",
        "Sarsod",
        "Sasaram",
        "Sasvad",
        "Satana",
        "Satara",
        "Sathyamangalam",
        "Satna",
        "Sattenapalle",
        "Sattur",
        "Saunda",
        "Saundatti-Yellamma",
        "Sausar",
        "Savanur",
        "Savarkundla",
        "Savner",
        "Sawai Madhopur",
        "Sawantwadi",
        "Sedam",
        "Sehore",
        "Sendhwa",
        "Seohara",
        "Seoni",
        "Seoni-Malwa",
        "Shahabad",
        "Shahabad, Hardoi",
        "Shahabad, Rampur",
        "Shahade",
        "Shahbad",
        "Shahdol",
        "Shahganj",
        "Shahjahanpur",
        "Shahpur",
        "Shahpura",
        "Shahpura",
        "Shajapur",
        "Shamgarh",
        "Shamli",
        "Shamsabad, Agra",
        "Shamsabad, Farrukhabad",
        "Shegaon",
        "Sheikhpura",
        "Shendurjana",
        "Shenkottai",
        "Sheoganj",
        "Sheohar",
        "Sheopur",
        "Sherghati",
        "Sherkot",
        "Shiggaon",
        "Shikaripur",
        "Shikarpur, Bulandshahr",
        "Shikohabad",
        "Shillong",
        "Shimla",
        "Shirdi",
        "Shirpur-Warwade",
        "Shirur",
        "Shishgarh",
        "Shivamogga",
        "Shivpuri",
        "Sholavandan",
        "Sholingur",
        "Shoranur",
        "Shrigonda",
        "Shrirampur",
        "Shrirangapattana",
        "Shujalpur",
        "Siana",
        "Sibsagar",
        "Siddipet",
        "Sidhi",
        "Sidhpur",
        "Sidlaghatta",
        "Sihor",
        "Sihora",
        "Sikanderpur",
        "Sikandra Rao",
        "Sikandrabad",
        "Sikar",
        "Silao",
        "Silapathar",
        "Silchar",
        "Siliguri",
        "Sillod",
        "Silvassa",
        "Simdega",
        "Sindagi",
        "Sindhagi",
        "Sindhnur",
        "Singrauli",
        "Sinnar",
        "Sira",
        "Sircilla",
        "Sirhind Fatehgarh Sahib",
        "Sirkali",
        "Sirohi",
        "Sironj",
        "Sirsa",
        "Sirsaganj",
        "Sirsi",
        "Sirsi",
        "Siruguppa",
        "Sitamarhi",
        "Sitapur",
        "Sitarganj",
        "Sivaganga",
        "Sivagiri",
        "Sivakasi",
        "Siwan",
        "Sohagpur",
        "Sohna",
        "Sojat",
        "Solan",
        "Solapur",
        "Sonamukhi",
        "Sonepur",
        "Songadh",
        "Sonipat",
        "Sopore",
        "Soro",
        "Soron",
        "Soyagaon",
        "Sri Madhopur",
        "Srikakulam",
        "Srikalahasti",
        "Srinagar",
        "Srinagar",
        "Srinivaspur",
        "Srirampore",
        "Srisailam Project (Right Flank Colony) Township",
        "Srivilliputhur",
        "Sugauli",
        "Sujangarh",
        "Sujanpur",
        "Sullurpeta",
        "Sultanganj",
        "Sultanpur",
        "Sumerpur",
        "Sumerpur",
        "Sunabeda",
        "Sunam",
        "Sundargarh",
        "Sundarnagar",
        "Supaul",
        "Surandai",
        "Surapura",
        "Surat",
        "Suratgarh",
        "SUrban Agglomerationr",
        "Suri",
        "Suriyampalayam",
        "Suryapet",
        "Tadepalligudem",
        "Tadpatri",
        "Takhatgarh",
        "Taki",
        "Talaja",
        "Talcher",
        "Talegaon Dabhade",
        "Talikota",
        "Taliparamba",
        "Talode",
        "Talwara",
        "Tamluk",
        "Tanda",
        "Tandur",
        "Tanuku",
        "Tarakeswar",
        "Tarana",
        "Taranagar",
        "Taraori",
        "Tarbha",
        "Tarikere",
        "Tarn Taran",
        "Tasgaon",
        "Tehri",
        "Tekkalakote",
        "Tenali",
        "Tenkasi",
        "Tenu dam-cum-Kathhara",
        "Terdal",
        "Tezpur",
        "Thakurdwara",
        "Thammampatti",
        "Thana Bhawan",
        "Thane",
        "Thanesar",
        "Thangadh",
        "Thanjavur",
        "Tharad",
        "Tharamangalam",
        "Tharangambadi",
        "Theni Allinagaram",
        "Thirumangalam",
        "Thirupuvanam",
        "Thiruthuraipoondi",
        "Thiruvalla",
        "Thiruvallur",
        "Thiruvananthapuram",
        "Thiruvarur",
        "Thodupuzha",
        "Thoubal",
        "Thrissur",
        "Thuraiyur",
        "Tikamgarh",
        "Tilda Newra",
        "Tilhar",
        "Tindivanam",
        "Tinsukia",
        "Tiptur",
        "Tirora",
        "Tiruchendur",
        "Tiruchengode",
        "Tiruchirappalli",
        "Tirukalukundram",
        "Tirukkoyilur",
        "Tirunelveli",
        "Tirupathur",
        "Tirupathur",
        "Tirupati",
        "Tiruppur",
        "Tirur",
        "Tiruttani",
        "Tiruvannamalai",
        "Tiruvethipuram",
        "Tiruvuru",
        "Tirwaganj",
        "Titlagarh",
        "Tittakudi",
        "Todabhim",
        "Todaraisingh",
        "Tohana",
        "Tonk",
        "Tuensang",
        "Tuljapur",
        "Tulsipur",
        "Tumkur",
        "Tumsar",
        "Tundla",
        "Tuni",
        "Tura",
        "Uchgaon",
        "Udaipur",
        "Udaipur",
        "Udaipurwati",
        "Udgir",
        "Udhagamandalam",
        "Udhampur",
        "Udumalaipettai",
        "Udupi",
        "Ujhani",
        "Ujjain",
        "Umarga",
        "Umaria",
        "Umarkhed",
        "Umbergaon",
        "Umred",
        "Umreth",
        "Una",
        "Unjha",
        "Unnamalaikadai",
        "Unnao",
        "Upleta",
        "Uran Islampur",
        "Uran",
        "Uravakonda",
        "Urmar Tanda",
        "Usilampatti",
        "Uthamapalayam",
        "Uthiramerur",
        "Utraula",
        "Vadakkuvalliyur",
        "Vadalur",
        "Vadgaon Kasba",
        "Vadipatti",
        "Vadnagar",
        "Vadodara",
        "Vaijapur",
        "Vaikom",
        "Valparai",
        "Valsad",
        "Vandavasi",
        "Vaniyambadi",
        "Vapi",
        "Vapi",
        "Varanasi",
        "Varkala",
        "Vasai-Virar",
        "Vatakara",
        "Vedaranyam",
        "Vellakoil",
        "Vellore",
        "Venkatagiri",
        "Veraval",
        "Vidisha",
        "Vijainagar, Ajmer",
        "Vijapur",
        "Vijayapura",
        "Vijayawada",
        "Vijaypur",
        "Vikarabad",
        "Vikramasingapuram",
        "Viluppuram",
        "Vinukonda",
        "Viramgam",
        "Virudhachalam",
        "Virudhunagar",
        "Visakhapatnam",
        "Visnagar",
        "Viswanatham",
        "Vita",
        "Vizianagaram",
        "Vrindavan",
        "Vyara",
        "Wadgaon Road",
        "Wadhwan",
        "Wadi",
        "Wai",
        "Wanaparthy",
        "Wani",
        "Wankaner",
        "Wara Seoni",
        "Warangal",
        "Wardha",
        "Warhapur",
        "Warisaliganj",
        "Warora",
        "Warud",
        "Washim",
        "Wokha",
        "Yadgir",
        "Yamunanagar",
        "Yanam",
        "Yavatmal",
        "Yawal",
        "Yellandu",
        "Yemmiganur",
        "Yerraguntla",
        "Yevla",
        "Zaidpur",
        "Zamania",
        "Zira",
        "Zirakpur",
        "Zunheboto",
    ]

    let [addressType, setaddresstype] = useState("")
    let [buildingName, setbuildingname] = useState("")
    let [house_number, sethousenumber] = useState("")
    let [landmark, setlandmark] = useState("")
    let [city, setcity] = useState("select city")
    let [state, setstate] = useState("select state")
    let [pincode, setpincode] = useState()
    let [country, setcountry] = useState("select country")
    let data = { addressType, house_number, buildingName, landmark, city, country, state, pincode }
    let user = JSON.parse(localStorage.getItem("User"))
    let addAddress = () => {
        // e.preventDefault()
        axios.post(`http://localhost:8080/addresses/${user.id}`, data)
            .then((res) => {
                console.log(res.data.body);
                alert("Address Has Been Saved")
            })
            .catch((err) => {
                console.log(err.data);
                alert("Invalid Data")
            })
    }
    return (
        <div className="add-address">
            <form action="" onSubmit={addAddress}>
                <label htmlFor="">Address Type</label>
                <input type="text" value={addressType} onChange={(e) => { setaddresstype(e.target.value) }} placeholder="Enter address type" />
                <label htmlFor="">House_No:</label>
                <input type="text" value={house_number} onChange={(e) => { sethousenumber(e.target.value) }} placeholder="Enter house_no" />
                <label htmlFor="">Building Name:</label>
                <input type="text" value={buildingName} onChange={(e) => { setbuildingname(e.target.value) }} placeholder="Enter Building name" />
                <label htmlFor="">Landmark:</label>
                <input type="text" value={landmark} onChange={(e) => { setlandmark(e.target.value) }} placeholder="enter ur landmark" />
                <label htmlFor="">Country</label>
                <select value={country} onChange={(e) => { setcountry(e.target.value) }}>
                    {countryList.map((x) => { return (<><option>{x.name}</option></>) })}
                </select>
                <label htmlFor="">State</label>
                <select value={state} onChange={(e) => { setstate(e.target.value) }}>
                    {stateList.map((x) => { return (<option>{x.state}</option>) })}
                </select>
                <label htmlFor="">City</label>
                <select value={city} onChange={(e) => { setcity(e.target.value) }}>
                    {cityList.map((x) => { return (<><option>{x}</option></>) })}
                </select>

                <label htmlFor="">Pincode:</label>
                <input type="text" value={pincode} onChange={(e) => { setpincode(e.target.value) }} placeholder="Enter ur pincode" />
                <button className="btn btn-outline-success btn-warning">submit</button>
            </form>
        </div>
    );
}

export default AddAddress;